[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SparseCNN"
version = "0.1.0"
description = "Sparse Convolutional Neural Network (SCNN) for Neutrino Physics experiment"
authors = [{ name="Haejun (Stella) Oh", email="haejunoh74@gmail.com" }]

